# Generated by Django 6.0.3 on 2026-05-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credential_requests', '0003_request_processed_at_alter_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='est_release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
