# Generated by Django 6.0.3 on 2026-05-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credential_requests', '0004_alter_request_est_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='document_summary',
            field=models.TextField(blank=True, help_text='Summary of all documents requested and their copies', null=True),
        ),
    ]
