# Generated by Django 6.0.3 on 2026-05-25 11:07

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studentprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='id_image',
            field=models.ImageField(blank=True, null=True, upload_to='id_images/', validators=[accounts.models.validate_image_extension, accounts.models.validate_image_size]),
        ),
    ]
