# Generated by Django 6.0.3 on 2026-05-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='verification_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
