# Generated by Django 6.0.3 on 2026-05-25 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_studentprofile_id_image_optional'),
        ('accounts', '0004_studentprofile_verification_notes'),
    ]

    operations = [
    ]
